// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjf3p5I76hIBr789rgGmL3iB4yzFeOEEk',
    appId: '1:275327667668:web:91bdb06ff48bef86685a41',
    messagingSenderId: '275327667668',
    projectId: 'fungid-app',
    authDomain: 'fungid-app.firebaseapp.com',
    storageBucket: 'fungid-app.appspot.com',
    measurementId: 'G-S0Z0XJ5C8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPprZNOuaL62YjlkRw-a8qSvix3JzHEy0',
    appId: '1:275327667668:android:f6ffcd16bb586e5a685a41',
    messagingSenderId: '275327667668',
    projectId: 'fungid-app',
    storageBucket: 'fungid-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGu4s_cUsLwNrG1YLKKDYDAG9sz1qyfGQ',
    appId: '1:275327667668:ios:10fcbbcba6b8f437685a41',
    messagingSenderId: '275327667668',
    projectId: 'fungid-app',
    storageBucket: 'fungid-app.appspot.com',
    iosClientId: '275327667668-5rhm8frpf6rabem47g841i9bcr58u2pm.apps.googleusercontent.com',
    iosBundleId: 'app.fungid.fungidapp',
  );
}
