# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    upload_to_testflight(
      ipa: "../build/ios/ipa/fungid_flutter.ipa",
      skip_waiting_for_build_processing: true,
    )
  end

  lane :upload do
    upload_to_app_store(
      ipa: "../build/ios/ipa/fungid_flutter.ipa",
      automatic_release: true,
      force: true,
    )
  end

  lane :crashlytics do
    upload_symbols_to_crashlytics(dsym_path: "./Runner.app.dSYM.zip")
  end
end
