# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

app_team_id = 'AB83BKF89B'
itc_team_id = '1384242'
itc_provider_id = 'AwesomeOrgLLC'


platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )
    # https://github.com/fastlane/fastlane/issues/20773
    ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = "true"

    upload_to_testflight(
      itc_provider: "QVF4W6GHP4",
      ipa: "../build/ios/ipa/fungid_flutter.ipa"
    )
  end

  lane :upload do
    # https://github.com/fastlane/fastlane/issues/20773
    ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = "true"

    # upload_to_testflight(
    #   itc_provider: "QVF4W6GHP4",
    #   ipa: "../build/ios/ipa/fungid_flutter.ipa"
    # )
    upload_to_app_store(
      itc_provider: "QVF4W6GHP4",
      ipa: "../build/ios/ipa/fungid_flutter.ipa",
      automatic_release: true,
    )

  end

  lane :crashlytics do
    upload_symbols_to_crashlytics(dsym_path: "./Runner.app.dSYM.zip")
  end
end
