# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :draft do
    # crashlytics
  
    upload_to_play_store(
      track: 'beta',
      release_status: 'draft',
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
  
  lane :internal do
    # crashlytics
  
    upload_to_play_store_internal_app_sharing(
      # track: 'internal',
      # release_status: 'draft',
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
  

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(aab: "../build/app/outputs/bundle/release/app-release.aab")
  end
end
